### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by szogi1910** [MitchDizzle/Advanced-Admin-ESP#17]
Hi, after uploading the plugin, the server gets a crash

https://crash.limetech.org/jchjhvi3nw4n

**Comment by MitchDizzle** [comment]
The crash mentions dhook, 443 other reports have been made similar, I'm going to go ahead and close this. The crash isn't from this plugin, I've already stress-tested it a ton also on the new update and didn't find any crashes.
