### ISSUE TITLE
After last update it's flood in chat

### ISSUE THREAD

**Issue by Allower** [MitchDizzle/Advanced-Admin-ESP#18]
Every kill or round start or round end it's flood/spam in chat with skin numbers

> Skin 109
> Skin 118
> Skin 119
> Skin 120
> Skin 131
> Skin 132
> Skin 133
> Skin 134
> Skin 144
> Skin 145
> Skin 146
> Skin 147
> Skin 153
> Skin 154
> Skin 155
> Skin 157
> Skin 158

Screenshot below, all players see this
![20181210200053_1](https://user-images.githubusercontent.com/7057182/49748340-7c08d080-fcb6-11e8-887b-949c362f6929.jpg)

**Comment by MitchDizzle** [comment]
Use the latest version
