### ISSUE TITLE
ESP when in spec or dead

### ISSUE THREAD

**Issue by Czar-VG** [MitchDizzle/Advanced-Admin-ESP#6]
Cannot seem to get the esp to work when in spec or dead. Works fine when alive. Using version 1.3.1. sm_advanced_esp_lifestate "0"

**Comment by TR1D** [comment]
+1

**Comment by MitchDizzle** [comment]
What are your config settings

**Comment by Czar-VG** [comment]
`// This file was auto-generated by SourceMod (v1.8.0.5967)
// ConVars for plugin "csgo_advanced_esp.smx"


// Determines R G B A glow colors for Counter-Terrorists team
// Format should be "R G B A" (with spaces)
// -
// Default: "96 128 192 64"
sm_advanced_esp_ctcolor "96 128 192 64"

// Set to 1 if admins should automatically be given ESP
// -
// Default: "0"
sm_advanced_esp_default "0"

// Set to 1 if admins should only see esp when dead, 2 to only see esp while alive, 0 dead or alive.
// -
// Default: "0"
sm_advanced_esp_lifestate "0"

// Set to 1 if giving and setting esp should notify the rest of the server.
// -
// Default: "0"
sm_advanced_esp_notify "0"

// Determines R G B A glow colors for Terrorists team
// Set to "0 0 0 0" to disable
// -
// Default: "192 160 96 64"
sm_advanced_esp_tcolor "192 160 96 64"

`

**Comment by MitchDizzle** [comment]
what about sm_advanced_esp_team?

**Comment by MitchDizzle** [comment]
I've pushed an update for the Dead players seeing glows, however I'm going to have to rewrite a few things for spectators to be able to see the glows. May take some time.

**Comment by TR1D** [comment]
Fixed

**Comment by MitchDizzle** [comment]
Verified by user inspection
